# Backend configuration
backend:
  name: cmoralesbackend
  image: docker.io/rkaeffer/codelab-gitops-backend:1.0.0
  containerPort: 8080
  host: christian.morales-backend.codelab.cloud-sp.eu
  service:
    port: 443
frontend:
  name: cmoralesfrontend
  image: docker.io/rkaeffer/codelab-gitops-frontend:1.0.0
  containerPort: 4200
  host: christian.morales-frontend.codelab.cloud-sp.eu
  service:
    port: 443